function checkoutui(cOut)

mainscreen = figure('Name','Main Screen');
pos = get(mainscreen,'Position');
set(mainscreen,'Position',[pos(1:2),400,400]);
toolpurchPanel = uipanel('Parent',mainscreen,'Position',[0,.3,1,1]);
addPanel = uipanel('Parent',mainscreen,'Position',[0,0,1,.3]);
orText = uicontrol(mainscreen,'Style','text',...
                        'String','-OR-',...
                        'FontSize',20,...
                        'Units','normalized',...
                        'Position',[.4,.27,.2,.08]);

% The person's status/title: Staff/Student/Mentor/Teacher
statusText = uicontrol(toolpurchPanel,'Style','text',...
                        'FontSize',12,...
                        'String','Status',...
                        'Units','normalized',...
                        'Position',[.25,.56,.5,.1]);
statusPopup = uicontrol(toolpurchPanel,'Style','popup',...
                        'String',{'Student','Mentor'},...
                        'Units','normalized',...
                        'FontSize',10,...   
                        'Position',[.25,.53,.5,.08]);

% The person's name
personText = uicontrol(toolpurchPanel,'Style','text',...
                        'FontSize',12,...
                        'String','Name',...
                        'Units','normalized',...
                        'Position',[.25,.4,.5,.1]);
personEdit = uicontrol(toolpurchPanel,'Style','edit',...
                        'Units','normalized',...
                        'FontSize',10,...
                        'Position',[.25,.37,.5,.08]);
                    
% Tool button
toolButton = uicontrol(toolpurchPanel,'Style','pushbutton',...
                        'Units','normalized',...
                        'FontSize',20,...
                        'String','Tool',...
                        'Position',[.1,.07,.35,.22],...
                        'Callback',{@tool_callback});

% Purchase button
purchaseButton = uicontrol(toolpurchPanel,'Style','pushbutton',...
                        'Units','normalized',...
                        'FontSize',20,...
                        'String','Purchase',...
                        'Position',[.55,.07,.35,.22],...
                        'Callback',{@purchase_callback});
                    
% Add button
addButton = uicontrol(addPanel,'Style','pushbutton',...
                        'Units','normalized',...
                        'FontSize',20,...
                        'String','Add',...
                        'Position',[.15,.25,.7,.5],...
                        'Callback',{@add_callback});
                    
    % Callback for the Tool button
    function tool_callback(obj,eventdata)
        set(addPanel,'Visible','off');
        set(toolpurchPanel,'Visible','off');
        set(orText,'Visible','off');
        set(mainscreen,'Position',[pos(1:2),700,400]);
        set(mainscreen,'Name','Tool Checkout');
        
        leftPanel = uipanel('Parent',mainscreen,'Position',[0,.15,.5,1]);
        rightPanel = uipanel('Parent',mainscreen,'Position',[.5,.15,1,1]);
        bottomlPanel = uipanel('Parent',mainscreen,'Position',[0,0,.5,.15]);
        bottomrPanel = uipanel('Parent',mainscreen,'Position',[.5,0,1,.15]);
        
        % Back button
        tool_backButton = uicontrol(bottomrPanel,'Style','pushbutton',...
                                    'String','Back',...
                                    'FontSize',12,...
                                    'Units','normalized',...
                                    'Position',[.05,.2,.4,.6],...
                                    'Callback',{@toolBack_callback});
                                
        % Staff Check
        tool_staffText = uicontrol(bottomlPanel,'Style','text',...
                                    'String','Staff Name:',...
                                    'FontSize',10,...
                                    'Units','normalized',...
                                    'Position',[.025,.175,.2,.5]);
        tool_staffEdit = uicontrol(bottomlPanel,'Style','edit',...
                                    'FontSize',12,...
                                    'Units','normalized',...
                                    'Position',[.25,.25,.675,.5]);
                                
        % Person's School
        tool_schoolText = uicontrol(leftPanel,'Style','text',...
                                    'String','School Name',...
                                    'FontSize',15,...
                                    'Units','normalized',...
                                    'Position',[.125,.7,.75,.1]);
        tool_schoolEdit = uicontrol(leftPanel,'Style','edit',...
                                    'FontSize',15,...
                                    'Units','normalized',...
                                    'Position',[.125,.625,.75,.1]);
                                
        % Tools already checked out
        tool_checkedoutText = uicontrol(leftPanel,'Style','text',...
                                    'String','Tools Checked Out',...
                                    'FontSize',15,...
                                    'Units','normalized',...
                                    'Position',[.125,.5,.75,.1]);
        %%% INSERT CODE FOR UITABLE %%%%
        
        % Tool to be checked out/in
        tool_Text = uicontrol(rightPanel,'Style','text',...
                                    'String','Tool Name',...
                                    'FontSize',15,...
                                    'Units','normalized',...
                                    'Position',[0,.7,.5,.1]);
        tool_Edit = uicontrol(rightPanel,'Style','edit',...
                                    'FontSize',15,...
                                    'Units','normalized',...
                                    'Position',[.1,.63,.3,.1]);
        
        % Quantity to be checked out
        tool_quantityText = uicontrol(rightPanel,'Style','text',...
                                    'String','Quantity',...
                                    'FontSize',15,...
                                    'Units','normalized',...
                                    'Position',[0,.5,.5,.1]);
        tool_quantityEdit = uicontrol(rightPanel,'Style','edit',...
                                    'FontSize',15,...
                                    'Units','normalized',...
                                    'Position',[.1,.43,.3,.1]);
        
        % Check Out button
        tool_checkoutButton = uicontrol(rightPanel,'Style','pushbutton',...
                                    'String','Check Out',...
                                    'FontSize',15,...
                                    'Units','normalized',...
                                    'Position',[.25,.125,.2,.2],...
                                    'Callback',{@toolCheckOut_callback});
        
        % Check In button
        tool_checkinButton = uicontrol(rightPanel,'Style','pushbutton',...
                                    'String','Return',...
                                    'FontSize',15,...
                                    'Units','normalized',...
                                    'Position',[.05,.125,.2,.2],...
                                    'Callback',{@toolCheckIn_callback});
                                
           % Start Sam's code ######################
        
        %statText = get(statusPopup,'String'); % might change
        statText = get(statusPopup,'Value');
        nameText = get(personEdit,'String');
        
        if statText==1
            studentArr=cOut.Students;
            b = false;
            for i = 1:length(studentArr)
                if strcmp(nameText,studentArr{i}.Name)
                    b = true;
                end
            end
            
            if b
                % do nothing
            else
                errordlg(sprintf('%s does not exist', nameText),'Error')
            end
        elseif statText==2
            mentArr=cOut.Mentors;
            b = false;
            for i = 1:length(mentArr)
                if strcmp(nameText,mentArr{i}.Name)
                    b = true;
                end
            end
            
            if b
                % do nothing
            else
                errordlg(sprintf('%s does not exist', nameText),'Error')
            end
            
        end
                 
        % End Sam's code #######################
                             
                                
        function toolCheckIn_callback(obj,eventdata)
            % ADD CODE HERE
        end
        
        function toolCheckOut_callback(obj,eventdata)
            % ADD CODE HERE
        end
        
        function toolBack_callback(obj,eventdata)
            close(mainscreen);
            checkoutui();
        end

    end

    % Callback for the Purchase button
    function purchase_callback(obj,eventdata)
        set(addPanel,'Visible','off');
        set(toolpurchPanel,'Visible','off');
        set(orText,'Visible','off');
        set(mainscreen,'Position',[pos(1:2),700,400]);
        set(mainscreen,'Name','Purchasable Screen');
        
        leftPanel = uipanel('Parent',mainscreen,'Position',[0,.15,.5,1]);
        rightPanel = uipanel('Parent',mainscreen,'Position',[.5,.15,1,1]);
        bottomlPanel = uipanel('Parent',mainscreen,'Position',[0,0,.5,.15]);
        bottomrPanel = uipanel('Parent',mainscreen,'Position',[.5,0,1,.15]);
        
        % Back button
        purchase_backButton = uicontrol(bottomrPanel,'Style','pushbutton',...
                                        'String','Back',...
                                        'FontSize',12,...
                                        'Units','normalized',...
                                        'Position',[.05,.2,.4,.6],...
                                        'Callback',{@purchaseBack_callback});
        
        % Staff Name
        purchase_staffText = uicontrol(bottomlPanel,'Style','Text',...
                                        'String','Staff Name:',...
                                        'FontSize',10,...
                                        'Units','normalized',...
                                        'Position',[.025,.175,.2,.5]);
        purchase_staffEdit = uicontrol(bottomlPanel,'Style','edit',...
                                        'FontSize',12,...
                                        'Units','normalized',...
                                        'Position',[.25,.25,.675,.5]);
                                    
        % Person's School
        purchase_schoolText = uicontrol(leftPanel,'Style','text',...
                                        'String','School Name',...
                                        'FontSize',12,...
                                        'Units','normalized',...
                                        'Position',[.125,.725,.75,.1]);
        purchase_schoolEdit = uicontrol(leftPanel,'Style','edit',...
                                        'FontSize',15,...
                                        'Units','normalized',...
                                        'Position',[.125,.675,.75,.1]);
        
        % School's remaining PandaPoints
        purchase_pointsText = uicontrol(leftPanel,'Style','text',...
                                        'String','Remaining PandaPoints',...
                                        'FontSize',12,...
                                        'Units','normalized',...
                                        'Position',[.125,.55,.75,.1]);
        purchase_pointsEdit = uicontrol(leftPanel,'Style','edit',...
                                        'FontSize',15,...
                                        'Units','normalized',...
                                        'Position',[.125,.5,.75,.1]);
        
        % Past purchases
        purchase_purchasesText = uicontrol(leftPanel,'Style','text',...
                                        'String','Purchases',...
                                        'FontSize',12,...
                                        'Units','normalized',...
                                        'Position',[.125,.375,.75,.1]);
        %%% INSERT CODE HERE %%%
        
        % Item to be purchased/returned
        purchase_itemText = uicontrol(rightPanel,'Style','text',...
                                        'String','Purchasable',...
                                        'FontSize',12,...
                                        'Units','normalized',...
                                        'Position',[0,.7,.5,.1]);
        purchase_itemEdit = uicontrol(rightPanel,'Style','edit',...
                                        'FontSize',15,...
                                        'Unit','normalized',...
                                        'Position',[.1,.65,.3,.1]);
                                    
        % Quantity to be purchased/returned
% Quantity to be purchased/returned
        purchase_quantityText = uicontrol(rightPanel,'Style','text',...
                                        'String','Quantity',...
                                        'FontSize',12,...
                                        'Units','normalized',...
                                        'Position',[0,.525,.335,.1]);
        purchase_quantityEdit = uicontrol(rightPanel,'Style','edit',...
                                        'FontSize',15,...
                                        'Units','normalized',...
                                        'Position',[.1,.475,.135,.1]);
                                    
        % Update button
        purchase_updateButton = uicontrol(rightPanel,'Style','pushbutton',...
                                        'String','Update',...
                                        'FontSize',15,...
                                        'Units','normalized',...
                                        'Position',[.26,.475,.135,.125],...
                                        'Callback',@purchaseUpdate_callback);
                                    
        % Cost of purchase
        purchase_costText = uicontrol(rightPanel,'Style','text',...
                                        'String','Cost',...
                                        'FontSize',12,...
                                        'Units','normalized',...
                                        'Position',[0,.35,.5,.1]);
        purchase_costEdit = uicontrol(rightPanel,'Style','edit',...
                                        'FontSize',15,...
                                        'Units','normalized',...
                                        'Position',[.1,.3,.3,.1]);
                                    
        % Return button
        purchase_returnButton = uicontrol(rightPanel,'Style','pushbutton',...
                                        'String','Return',...
                                        'FontSize',15,...
                                        'Units','normalized',...
                                        'Position',[.05,.075,.2,.15],...
                                        'Callback',{@purchaseReturn_callback});
        
        % Buy button
        purchase_buyButton = uicontrol(rightPanel,'Style','pushbutton',...
                                        'String','Buy',...
                                        'FontSize',15,...
                                        'Units','normalized',...
                                        'Position',[.25,.075,.2,.15],...
                                        'Callback',{@purchaseBuy_callback});
        
        function purchaseUpdate_callback(obj,eventdata)
           % ADD CODE HERE
           item = get(purchase_itemEdit,'String');
           quantity = get(purchase_quantityEdit,'String');
           if ~isempty(item) && ~isempty(quantity)
               
           else
               errordlg('You need to fill out both Purchasable and Quantity Fields','Error');
           end
        end
                                    
        function purchaseReturn_callback(obj,eventdata)
            % ADD CODE HERE
            item = get(purchase_itemEdit,'String');
            quantity = get(purchase_quantityEdit,'String');
            cost = get(purchase_costEdit,'String');
            if ~isempty(item) && ~isempty(quantity) && ~isempty(cost)
                
            else
                errordlg('You need to fill out and update all the fields','Error');
            end
        end
        
        function purchaseBuy_callback(obj,eventdata)
            % ADD CODE HERE
            item = get(purchase_itemEdit,'String');
            quantity = get(purchase_quantityEdit,'String');
            cost = get(purchase_costEdit,'String');
            if ~isempty(item) && ~isempty(quantity) && ~isempty(cost)
                
            else
                errordlg('You need to fill out and update all the fields','Error');
            end
        end
                                    
        function purchaseBack_callback(obj,eventdata)
            close(mainscreen);
            checkoutui();
        end
        
    end

    % Callback for the Add button
    function add_callback(obj,eventdata)
        set(addPanel,'Visible','off');
        set(toolpurchPanel,'Visible','off');
        set(orText,'Visible','off');
        set(mainscreen,'Position',[pos(1:2),600,150]);
        set(mainscreen,'Name','Add Screen');
        
        addPanel2 = uipanel('Parent',mainscreen,'Position',[0,0,1,1]);
        
        % Add Person button
        addPersonButton = uicontrol(addPanel2,'Style','pushbutton',...
                                    'String','Person',...
                                    'Units','normalized',...
                                    'FontSize',15,...
                                    'Position',[.075,.5,.25,.3],...
                                    'Callback',{@addPerson_callback});
        % Add Tool button
        addToolButton = uicontrol(addPanel2,'Style','pushbutton',...
                                    'String','Tool',...
                                    'Units','normalized',...
                                    'FontSize',15,...
                                    'Position',[.375,.5,.25,.3],...
                                    'Callback',{@addTool_callback});
        % Add Purchasable button
        addPurchaseButton = uicontrol(addPanel2,'Style','pushbutton',...
                                    'String','Purchasable',...
                                    'Units','normalized',...
                                    'FontSize',15,...
                                    'Position',[.675,.5,.25,.3],...
                                    'Callback',{@addPurchase_callback});
                                
        % Back button
        addBackButton = uicontrol(addPanel2,'Style','pushbutton',...
                                    'String','Back',...
                                    'Units','normalized',...
                                    'FontSize',12,...
                                    'Position',[.425,.15,.15,.25],...
                                    'Callback',{@addBack_callback});

        % Callback for the Add Person button
        function addPerson_callback(obj,eventdata)
            set(addPanel2,'Visible','off');
            set(mainscreen,'Position',[pos(1:2),300,300]);
            set(mainscreen,'Name','Add a Person');
            
            addPerson_panel = uipanel('Parent',mainscreen,'Position',[0,0,1,1]);

            % The person's status/title: Staff/Student/Mentor/Teacher
            person_statusText = uicontrol(addPerson_panel,'Style','text',...
                                        'String','Status',...
                                        'Units','normalized',...
                                        'FontSize',12,...
                                        'Position',[.125,.84,.75,.1]);
            person_statusPopup = uicontrol(addPerson_panel,'Style','popup',...
                                        'FontSize',12,...
                                        'String',{'Student','Mentor','Teacher','Staff'},...
                                        'Units','normalized',...
                                        'Position',[.125,.77,.75,.1]);

            % The person's name
            person_nameText = uicontrol(addPerson_panel,'Style','text',...
                                        'String','Name',...
                                        'Units','normalized',...
                                        'FontSize',12,...
                                        'Position',[.125,.65,.75,.1]);
            person_nameEdit = uicontrol(addPerson_panel,'Style','edit',...
                                        'FontSize',12,...
                                        'Units','normalized',...
                                        'Position',[.125,.58,.75,.1]);

            % The person's school
            person_schoolText = uicontrol(addPerson_panel,'Style','text',...
                                        'String','School',...
                                        'Units','normalized',...
                                        'FontSize',12,...
                                        'Position',[.125,.46,.75,.1]);
            person_schoolEdit = uicontrol(addPerson_panel,'Style','edit',...
                                        'FontSize',12,...
                                        'Units','normalized',...
                                        'Position',[.125,.39,.75,.1]);

            % Add button
            person_addButton = uicontrol(addPerson_panel,'Style','pushbutton',...
                                        'FontSize',12,...
                                        'String','Add',...
                                        'Units','normalized',...
                                        'Position',[.55,.1,.3,.2],...
                                        'Callback',{@personAdd_callback});

            % Back button
            person_backButton = uicontrol(addPerson_panel,'Style','pushbutton',...
                                        'FontSize',12,...
                                        'String','Back',...
                                        'Units','normalized',...
                                        'Position',[.125,.1,.3,.2],...
                                        'Callback',{@personBack_callback});
                                    
            % Back button callback                        
            function personBack_callback(obj,eventdata)
                add_callback;
                set(addPerson_panel,'Visible','off');
            end
            
            % Add button callback
            function personAdd_callback(obj,eventdata)
                % ADD CODE HERE
            end
        end
        
        % Callback for the Add Tool button
        function addTool_callback(obj,eventdata)
            set(addPanel2,'Visible','off');
            set(mainscreen,'Position',[pos(1:2),300,300]);
            set(mainscreen,'Name','Add a Tool');
            
            addTool_panel = uipanel('Parent',mainscreen,'Position',[0,0,1,1]);
            
            % The name of the tool
            tool_nameText = uicontrol(addTool_panel,'Style','text',...
                                        'FontSize',12,...
                                        'String','Tool Name',...
                                        'Units','normalized',...
                                        'Position',[.125,.825,.75,.1]);
            tool_nameEdit = uicontrol(addTool_panel,'Style','edit',...
                                        'FontSize',12,...
                                        'Units','normalized',...
                                        'Position',[.125,.75,.75,.1]);
            
            % The code of the tool                        
            tool_codeText = uicontrol(addTool_panel,'Style','text',...
                                        'String','Tool Code',...
                                        'FontSize',12,...
                                        'Units','normalized',...
                                        'Position',[.125,.56,.75,.1]);
            tool_codeEdit = uicontrol(addTool_panel,'Style','edit',...
                                        'FontSize',12,...
                                        'Units','normalized',...
                                        'Position',[.125,.49,.75,.1]);
                                    
            % Back button
            tool_backButton = uicontrol(addTool_panel,'Style','pushbutton',...
                                        'String','Back',...
                                        'FontSize',12,...
                                        'Units','normalized',...
                                        'Position',[.125,.15,.3,.2],...
                                        'Callback',{@toolBack_callback});
                                
            % Add button
            tool_addButton = uicontrol(addTool_panel,'Style','pushbutton',...
                                        'String','Add',...
                                        'FontSize',12,...
                                        'Units','normalized',...
                                        'Position',[.55,.15,.3,.2],...
                                        'Callback',{@toolAdd_callback});
            
            % Back button callback
            function toolBack_callback(obj,eventdata)
                add_callback;
                set(addTool_panel,'Visible','off');
            end
            
            % Add button callback
            function toolAdd_callback(obj,eventdata)
                % INSERT CODE HERE
            end
        end
        
        % Callback for the Add Purchasable button
        function addPurchase_callback(obj,eventdata)
            set(addPanel2,'Visible','off');
            set(mainscreen,'Position',[pos(1:2),300,300]);
            set(mainscreen,'Name','Add a Purchasable');
            
            addPurchase_panel = uipanel('Parent',mainscreen,'Position',[0,0,1,1]);
            
            % The name of the Purchasable
            purchase_nameText = uicontrol(addPurchase_panel,'Style','text',...
                                        'String','Purchasable Name',...
                                        'FontSize',12,...
                                        'Units','normalized',...
                                        'Position',[.125,.85,.75,.1]);
            purchase_nameEdit = uicontrol(addPurchase_panel,'Style','edit',...
                                        'FontSize',12,...
                                        'Units','normalized',...
                                        'Position',[.125,.78,.75,.1]);
            
            % The code of the Purchasable
            purchase_codeText = uicontrol(addPurchase_panel,'Style','text',...
                                        'String','Purchasable Code',...
                                        'FontSize',12,...
                                        'Units','normalized',...
                                        'Position',[.125,.66,.75,.1]);
            purchase_codeEdit = uicontrol(addPurchase_panel,'Style','edit',...
                                        'FontSize',12,...
                                        'Units','normalized',...
                                        'Position',[.125,.59,.75,.1]);
            
            % The number of PandaPoints of the purchasable
            purchase_pointsText = uicontrol(addPurchase_panel,'Style','text',...
                                        'String','PandaPoint Cost',...
                                        'FontSize',12,...
                                        'Units','normalized',...
                                        'Position',[.125,.47,.75,.1]);
            purchase_pointsEdit = uicontrol(addPurchase_panel,'Style','edit',...
                                        'FontSize',12,...
                                        'Units','normalized',...
                                        'Position',[.125,.4,.75,.1]);
            
            % Back button 
            purchase_backbutton = uicontrol(addPurchase_panel,'Style','pushbutton',...
                                        'String','Back',...
                                        'FontSize',12,...
                                        'Units','normalized',...
                                        'Position',[.125,.1,.3,.2],...
                                        'Callback',{@purchaseBack_callback});
            
            % Add button 
            purchase_addbutton = uicontrol(addPurchase_panel,'Style','pushbutton',...
                                        'String','Add',...
                                        'FontSize',12,...
                                        'Units','normalized',...
                                        'Position',[.55,.1,.3,.2],...
                                        'Callback',{@purchaseAdd_callback});
            
            % Back button callback
            function purchaseBack_callback(obj,eventdata)
                add_callback;
                set(addPurchase_panel,'Visible','off');
            end
            
            % Add button callback
            function purchaseAdd_callback(obj,eventdata)
                % ADD CODE HERE
            end
        end
        
        % Callback for the Add Back button
        function addBack_callback(obj,eventdata)
            close(mainscreen);
            checkoutui();
        end
    end
end
